version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: edu-frontend:latest
    container_name: edu-frontend
    ports:
      - '8080:80'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    restart: always
