# Generated by Django 5.1.1 on 2024-10-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbilling',
            name='payment',
        ),
    ]
