# Generated by Django 5.1.1 on 2024-10-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbilling',
            name='course_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentbilling',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
