# Generated by Django 5.1.1 on 2024-10-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_studentbilling_course_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_payment',
            field=models.IntegerField(),
        ),
    ]
