# Generated by Django 5.1.1 on 2024-10-18 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_batch_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
