# Generated by Django 5.1.1 on 2024-10-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_alter_payment_options_remove_studentenroll_batch'),
        ('student', '0004_academicyear_created_at_academicyear_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='course_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentenroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
