# Generated by Django 5.1.1 on 2024-10-20 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_studentenroll_course_amount_and_more'),
        ('student', '0008_alter_academicyear_options_alter_day_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_type', models.CharField(blank=True, choices=[('poor', 'Poor'), ('meritorious', 'Meritorious'), ('ralative', 'Relatives'), ('friend', 'Friends'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='student.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
