# Generated by Django 5.1.1 on 2024-10-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_rename_price_course_course_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentbilling',
            old_name='course_amount',
            new_name='course_fee',
        ),
        migrations.RenameField(
            model_name='studentenroll',
            old_name='course_amount',
            new_name='course_fee',
        ),
    ]
