# Generated by Django 5.1.1 on 2025-03-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_college_status_district_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
