# Generated by Django 5.1.1 on 2024-10-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('roll', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('gurdian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ssc_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hsc_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.college')),
                ('home_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('hsc_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsc_batch', to='student.academicyear')),
                ('ssc_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssc_batch', to='student.academicyear')),
            ],
        ),
    ]
