# Generated by Django 5.1.1 on 2024-10-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_academicyear_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometown',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
