# Generated by Django 5.1.1 on 2024-10-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_day_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id']},
        ),
    ]
