# Generated by Django 5.1.1 on 2024-11-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_academicyear_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
