# Generated by Django 5.1.1 on 2024-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_roll',
            field=models.IntegerField(default=8, unique=True),
            preserve_default=False,
        ),
    ]
