# Generated by Django 5.1.1 on 2024-10-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnroll',
        ),
    ]
