# Generated by Django 5.1.1 on 2024-10-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_batch_status_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenroll',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
        ),
    ]
