# Generated by Django 5.1.1 on 2024-10-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_payment_amount_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='days',
            field=models.ManyToManyField(related_name='days', to='course.day'),
        ),
    ]
