# Generated by Django 5.1.1 on 2024-10-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_studentbilling_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbilling',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('tuition', 'Tuition Fee'), ('course', 'course Fee'), ('discount', 'Discount'), ('exam', 'Exam Fee'), ('material', 'Material Fee'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
