# Generated by Django 5.1.1 on 2024-10-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='course_fee',
        ),
    ]
