# Generated by Django 5.1.1 on 2024-10-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_rename_course_amount_studentbilling_course_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='amount',
            new_name='discount_amount',
        ),
    ]
