# Generated by Django 5.1.1 on 2024-10-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_rename_amount_discount_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_payment',
            new_name='payment_amount',
        ),
    ]
