# Generated by Django 5.1.1 on 2024-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_remove_studentbilling_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbilling',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('tuition', 'Tuition Fee'), ('course', 'Course Fee'), ('exam', 'Exam Fee'), ('material', 'Material Fee'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
