# Generated by Django 5.1.1 on 2025-03-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_studentbilling_fee_type_delete_batch_and_more'),
        ('student', '0015_alter_student_batch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentBilling',
            new_name='Fee',
        ),
    ]
