# Generated by Django 5.1.1 on 2024-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
