name: CI/CD to Docker Hub and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # - name: Print secrets.
      #   run: |
      #     echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
      #     echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/edu-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edu-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/edu-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edu-frontend:latest

  steps:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: deploy on EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/edu-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/edu-frontend:latest
            docker compose -f /home/${{ secrets.EC2_USER }}/docker-compose.yaml up -d
