name: CI/CD to Docker Hub and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Print secrets.
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/edu-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edu-backend:latest

      # - name: Build and push frontend image
      #   run: |
      #     docker build -t aplmahmud/edu-frontend:latest ./frontend
      #     # docker push aplmahmud/edu-frontend:latest
